/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.mariusklingl.wohnheim;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Student student1 = new Student("Marius", "Winf");
        WG wg1 = new WG();

        wg1.addStudent(student1);
        
        
        
        System.out.println(wg1.getWohnende());

    }
}
